name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Test (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "Running tests (first attempt)..."
          xvfb-run -a pnpm run test || {
            echo "First attempt failed. Retrying..."
            xvfb-run -a pnpm run test || {
              echo "Second attempt also failed. Exiting."
              exit 1
            }
          }

      - name: Test (non-Linux)
        if: runner.os != 'Linux'
        run: |
          echo "Running tests (first attempt)..."
          pnpm run test || (
            echo "First attempt failed. Retrying..." &&
            pnpm run test || (
              echo "Second attempt also failed. Exiting." &&
              exit 1
            )
          )